# Generated by Django 4.2.6 on 2023-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(default="No Level Specified", max_length=20),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(default="No description available.")),
                ("content", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="no-slug-description",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="blog_images/default.jpg", upload_to="blog_images/"
                    ),
                ),
            ],
        ),
    ]
